#!/bin/bash
# 一键创建GitHub仓库并部署

echo "正在为你创建GitHub仓库..."
echo ""
echo "请按照以下步骤操作："
echo ""
echo "方法1：使用浏览器（最简单）"
echo "================================"
echo "1. 点击这个链接：https://github.com/new"
echo ""
echo "2. 填写以下信息："
echo "   Repository name: oceano-crm-demo"
echo "   Description: 欧神诺CRM演示系统"
echo "   选择: Public (公开)"
echo "   ❌ 不要勾选任何其他选项"
echo ""
echo "3. 点击 'Create repository' 按钮"
echo ""
echo "4. 创建完成后，回到终端运行："
echo "   cd /Users/MurphyCom/Downloads/Antigravity"
echo "   git push -u origin gh-pages"
echo ""
echo "5. 然后在GitHub仓库页面："
echo "   Settings → Pages → Source 选择 'gh-pages' → Save"
echo ""
echo "================================"
echo ""
echo "完成后访问："
echo "https://happymurphy2026.github.io/oceano-crm-demo/"
echo ""
